"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.violationsRouter = void 0;
const express_1 = require("express");
const violations_controller_1 = require("./violations.controller");
const auth_middleware_1 = require("../../middleware/auth.middleware");
const rbac_middleware_1 = require("../../middleware/rbac.middleware");
const validate_middleware_1 = require("../../middleware/validate.middleware");
const violations_validation_1 = require("./violations.validation");
const router = (0, express_1.Router)();
exports.violationsRouter = router;
router.use(auth_middleware_1.authenticate);
router.post('/', (0, rbac_middleware_1.authorize)('admin', 'police'), (0, validate_middleware_1.validate)(violations_validation_1.createViolationSchema), violations_controller_1.violationsController.create);
router.get('/', (0, rbac_middleware_1.authorize)('admin', 'police', 'analyst'), (0, validate_middleware_1.validate)(violations_validation_1.violationQuerySchema, 'query'), violations_controller_1.violationsController.findAll);
router.get('/stats', (0, rbac_middleware_1.authorize)('admin', 'police', 'analyst'), violations_controller_1.violationsController.getStats);
router.get('/:id', (0, rbac_middleware_1.authorize)('admin', 'police', 'analyst'), violations_controller_1.violationsController.findById);
router.patch('/:id', (0, rbac_middleware_1.authorize)('admin', 'police'), (0, validate_middleware_1.validate)(violations_validation_1.updateViolationSchema), violations_controller_1.violationsController.update);
