"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.apiV1Router = void 0;
const express_1 = require("express");
const auth_routes_1 = require("../modules/auth/auth.routes");
const vehicles_routes_1 = require("../modules/vehicles/vehicles.routes");
const violations_routes_1 = require("../modules/violations/violations.routes");
const tracking_routes_1 = require("../modules/tracking/tracking.routes");
const alerts_routes_1 = require("../modules/alerts/alerts.routes");
const signals_routes_1 = require("../modules/traffic-signals/signals.routes");
const integration_routes_1 = require("../modules/integration/integration.routes");
const analytics_routes_1 = require("../modules/analytics/analytics.routes");
const challans_routes_1 = require("../modules/challans/challan.routes");
const movement_routes_1 = require("../modules/tracking/movement.routes");
const restricted_zones_routes_1 = require("../modules/restricted-zones/restricted-zones.routes");
const notif_prefs_routes_1 = require("../modules/notifications/notif-prefs.routes");
const accidents_routes_1 = require("../modules/accidents/accidents.routes");
const router = (0, express_1.Router)();
exports.apiV1Router = router;
router.use('/auth', auth_routes_1.authRouter);
router.use('/vehicles', vehicles_routes_1.vehiclesRouter);
router.use('/violations', violations_routes_1.violationsRouter);
router.use('/tracking', tracking_routes_1.trackingRouter);
router.use('/alerts', alerts_routes_1.alertsRouter);
router.use('/signals', signals_routes_1.signalsRouter);
router.use('/analytics', analytics_routes_1.analyticsRouter);
router.use('/challans', challans_routes_1.challansRouter);
router.use('/movement', movement_routes_1.movementRouter);
router.use('/restricted-zones', restricted_zones_routes_1.restrictedZonesRouter);
router.use('/notification-preferences', notif_prefs_routes_1.notifPrefsRouter);
router.use('/accidents', accidents_routes_1.accidentsRouter);
const audit_routes_1 = require("./audit");
router.use('/audit', audit_routes_1.auditRouter);
// AI microservice integration (service-to-service, API-key auth)
router.use('/integration', integration_routes_1.integrationRouter);
