"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.signalsRouter = void 0;
const express_1 = require("express");
const signals_controller_1 = require("./signals.controller");
const auth_middleware_1 = require("../../middleware/auth.middleware");
const rbac_middleware_1 = require("../../middleware/rbac.middleware");
const validate_middleware_1 = require("../../middleware/validate.middleware");
const signals_validation_1 = require("./signals.validation");
const router = (0, express_1.Router)();
exports.signalsRouter = router;
router.use(auth_middleware_1.authenticate);
router.post('/', (0, rbac_middleware_1.authorize)('admin'), (0, validate_middleware_1.validate)(signals_validation_1.createSignalSchema), signals_controller_1.signalsController.create);
router.get('/', (0, rbac_middleware_1.authorize)('admin', 'police', 'analyst'), (0, validate_middleware_1.validate)(signals_validation_1.signalQuerySchema, 'query'), signals_controller_1.signalsController.findAll);
router.get('/group/:groupId', (0, rbac_middleware_1.authorize)('admin', 'police', 'analyst'), signals_controller_1.signalsController.getGroupSignals);
router.get('/:id', (0, rbac_middleware_1.authorize)('admin', 'police', 'analyst'), signals_controller_1.signalsController.findById);
router.patch('/:id', (0, rbac_middleware_1.authorize)('admin'), (0, validate_middleware_1.validate)(signals_validation_1.updateSignalSchema), signals_controller_1.signalsController.update);
router.post('/:id/state', (0, rbac_middleware_1.authorize)('admin', 'police'), (0, validate_middleware_1.validate)(signals_validation_1.signalStateSchema), signals_controller_1.signalsController.changeState);
router.get('/:id/log', (0, rbac_middleware_1.authorize)('admin', 'police', 'analyst'), signals_controller_1.signalsController.getStateLog);
router.post('/:id/schedule', (0, rbac_middleware_1.authorize)('admin'), (0, validate_middleware_1.validate)(signals_validation_1.signalScheduleSchema), signals_controller_1.signalsController.createSchedule);
router.get('/:id/schedules', (0, rbac_middleware_1.authorize)('admin', 'police', 'analyst'), signals_controller_1.signalsController.getSchedules);
router.delete('/:id', (0, rbac_middleware_1.authorize)('admin'), signals_controller_1.signalsController.delete);
