"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.authRouter = void 0;
const express_1 = require("express");
const auth_controller_1 = require("./auth.controller");
const auth_middleware_1 = require("../../middleware/auth.middleware");
const validate_middleware_1 = require("../../middleware/validate.middleware");
const auth_validation_1 = require("./auth.validation");
const router = (0, express_1.Router)();
exports.authRouter = router;
router.post('/register', (0, validate_middleware_1.validate)(auth_validation_1.registerSchema), auth_controller_1.authController.register);
router.post('/login', (0, validate_middleware_1.validate)(auth_validation_1.loginSchema), auth_controller_1.authController.login);
router.post('/refresh', (0, validate_middleware_1.validate)(auth_validation_1.refreshTokenSchema), auth_controller_1.authController.refreshToken);
router.post('/logout', auth_middleware_1.authenticate, auth_controller_1.authController.logout);
router.post('/change-password', auth_middleware_1.authenticate, (0, validate_middleware_1.validate)(auth_validation_1.changePasswordSchema), auth_controller_1.authController.changePassword);
router.get('/profile', auth_middleware_1.authenticate, auth_controller_1.authController.getProfile);
